## Site metadata ##

title: AthleteFirst.Tokyo
description: Athlete First.

### Built settings ###

url: "https://athletefirst.github.io"
baseurl: "/tokyo"

github_username: AthleteFirst

theme: minima
